from _typeshed import OpenBinaryMode


1. 1 - TWO SUM:

2. 26 - REMOVE DUPLICATES FROM SORTED ARRAY:

3. 27 - REMOVE ELEMENT:

4. 35 - SEARCH INSERT POSITION:

5. 53 - MAXIMUM SUBARRAY:

6. 66 - PLUS ONE:

7. 88 - MERGE SORTED ARRAY:

8. 108 - CONVERT SORTED ARRAY TO BINARY SEARCH:

9. 118 - PASCALS TRIANGLE:

10. 119 - PASCALS TRAINGLE II: